name: SoCal Greek IV
favicon: null
layout_spectrum: 0.50362
typography_spectrum: 0.43739
title: SoCal Greek IV
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#5a6200'
    - '#737d03'
    - '#3d4200'
    - '#001f4c'
    - '#95a41a'
  brandStrength: 0.5859844372607768
  lightness: 0.4375
  saturation: 0.8102952542249113
  rhythmicContrast: 0.6143728061579168
purpose: []
