name: SoCal Greek IV
favicon: null
layout_spectrum: 0.98555
typography_spectrum: 0.43739
title: SoCal Greek IV
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#aee510'
    - '#94badb'
    - '#050fb5'
    - '#6b7781'
  brandStrength: 0.6875
  lightness: 0.375
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
